//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackagesProgram.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackagesProgram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adding the random value ended with en error: {0}, inner exception: {1}..
        /// </summary>
        internal static string AddToTableInterruptedMessage {
            get {
                return ResourceManager.GetString("AddToTableInterruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Problem with connection to database. Exception: {0}. Inner exception: {1}..
        /// </summary>
        internal static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The download of the ids was interrupted with an error: {0}. Inner exception: {1}.
        /// </summary>
        internal static string DownloadInterruptedMessage {
            get {
                return ResourceManager.GetString("DownloadInterruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your id is less or equal to 0. This is incorrect..
        /// </summary>
        internal static string IncorrectIdMessage {
            get {
                return ResourceManager.GetString("IncorrectIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your drawn number: {0}. This values exists in the database - try again..
        /// </summary>
        internal static string IncorrectNumberMessage {
            get {
                return ResourceManager.GetString("IncorrectNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You entered an incorrect range - intersection failed..
        /// </summary>
        internal static string IncorrectRangeMessage {
            get {
                return ResourceManager.GetString("IncorrectRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO PackagesIds (Id) VALUES (@Id).
        /// </summary>
        internal static string InsertCommand {
            get {
                return ResourceManager.GetString("InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inserting an id into packages table was interrupted with an error: {0}. Inner exception: {1}.
        /// </summary>
        internal static string InsertInterruptedMessage {
            get {
                return ResourceManager.GetString("InsertInterruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The specified range ({0} - {1}) is incorrect..
        /// </summary>
        internal static string RandomIdInterruptedMessage {
            get {
                return ResourceManager.GetString("RandomIdInterruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM PackagesIds.
        /// </summary>
        internal static string SelectAllRecordsFromPackagesTable {
            get {
                return ResourceManager.GetString("SelectAllRecordsFromPackagesTable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The starting value of the range is greater than/equal to the final number..
        /// </summary>
        internal static string StartAndFinalValueAreIncorrectMessage {
            get {
                return ResourceManager.GetString("StartAndFinalValueAreIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adding values to the table was successful..
        /// </summary>
        internal static string SuccessfulInsertMessage {
            get {
                return ResourceManager.GetString("SuccessfulInsertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have given too large a range. Maximum range is 0 - 10 000 000. Please change the range..
        /// </summary>
        internal static string TooBigRangeMessage {
            get {
                return ResourceManager.GetString("TooBigRangeMessage", resourceCulture);
            }
        }
    }
}
